name: import

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '10 * * * *'  # every hour at *:10

jobs:
  import:
    name: import
    runs-on: ubuntu-latest
    # continue-on-error: ${{ matrix.experimental }}
    steps:
      - name: Checkout iana-registries repo
        uses: actions/checkout@v2
        with:
          repository: ietf-tools/iana-registries
          token: ${{ secrets.IETF_BIB_BOT_PAT_IANA }}
          path: iana-registries

      - name: Setup Git
        run: |
          git config --global user.name ietf-bib-bot
          git config --global user.email gh-bib-bot@llc.ietf.org

      - name: Add GitHub remote to repo
        working-directory: iana-registries
        run: |
          git remote set-url origin \
            https://ietf-bib-bot:${{ secrets.IETF_BIB_BOT_PAT_IANA }}@github.com/ietf-tools/iana-registries

      - name: Perform rsync from IANA
        working-directory: iana-registries
        run: |
          rsync -avciz --delete-before \
            --exclude '.git*' \
            --exclude 'README.*' \
            rsync.iana.org::assignments .

      - name: Git diff
        working-directory: iana-registries
        run: |
          git diff

      - name: Skip the rest if no changes
        id: git_status
        working-directory: iana-registries
        run: |
          echo ::set-output name=STATUS::$(git status --porcelain | tr -d [:space:])

      - name: Add changes
        if: steps.git_status.outputs.STATUS != ''
        working-directory: iana-registries
        run: |
          git add -A
          git commit -m "$(date -R -u)"

      - name: Git log
        if: steps.git_status.outputs.STATUS != ''
        working-directory: iana-registries
        run: |
          git log | head -100

      - name: Git push to GitHub iana-registries
        if: steps.git_status.outputs.STATUS != ''
        working-directory: iana-registries
        run: |
          git push --all -f
          git push --tags -f

      - name: Checkout
        uses: actions/checkout@v2

      # Keeping the GHA workflow alive
      - uses: gautamkrishnar/keepalive-workflow@v1
        with:
          committer_username: ietf-bib-bot
          committer_email: gh-bib-bot@llc.ietf.org
